In [1]:
import torch
import torch.nn as nn
from torch.optim import RMSprop
import math
from dataclasses import dataclass
from typing import Optional, Tuple, List, Dict
import numpy as np
from scipy.optimize import minimize
from tqdm import tqdm
import pandas as pd
import os
from datetime import datetime
from functions import *
from evaluate import *
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
import warnings

warnings.filterwarnings("ignore")

In [2]:
# ticker_list = ['REE', 'SAM', 'HAP', 'GMD', 'GIL', 'TMS', 'SAV', 'DHA', 'MHC', 'HAS'] # 10 stocks with the most observations
ticker_list = ['REE', 'SAM', 'HAP'] # 3 stocks with the most observations
limits = {
    'hose':0.07,
    'hnx':0.1,
    'upcom':0.15
}
# Read and merge into 1 dataset

if "stock_data.csv" in os.listdir("data"):
    merged_df = pd.read_csv(
        os.path.join("data", "stock_data.csv"),
        index_col=None
    ).assign(
        date = lambda df : pd.to_datetime(df["date"])
    )
else:
    # Read and merge data
    hnx = pd.read_csv(os.path.join("data", "CafeF.HNX.Upto31.07.2025.csv")).assign(
        floor = "hnx"
    )
    hsx = pd.read_csv(os.path.join("data", "CafeF.HSX.Upto31.07.2025.csv")).assign(
        floor = "hose"
    )
    upcom = pd.read_csv(os.path.join("data", "CafeF.UPCOM.Upto31.07.2025.csv")).assign(
        floor = "upcom"
    )
    indexes = pd.read_csv(os.path.join("data", "CafeF.INDEX.Upto06.08.2025.csv")).assign(
        floor = "index"
    )

    # Rename columns
    hnx, hsx, upcom, indexes = [
        df.rename(columns={
            "<Ticker>":"ticker",
            "<DTYYYYMMDD>":"date",
            "<Open>":"open",
            "<High>":"high",
            "<Low>":"low",
            "<Close>":"close",
            "<Volume>":"volume"
        }) for df in [hnx, hsx, upcom, indexes]
    ]
        
    # Merge and clean data
    # UPCOM has missing tickers for some reason
    merged_df = pd.concat(
        [hnx, hsx, upcom, indexes],
        axis=0
    ).reset_index(drop=True).dropna(subset="ticker")\
    .assign(
        date=lambda df : df["date"].astype(str).apply(lambda x: datetime.strptime(x, "%Y%m%d").date())
    )
    merged_df.to_csv(
        os.path.join("data", "stock_data.csv"),
        index=False
    ) # Save merged data to save time in future runs


# Data cleaning and merging

data = merged_df[["date", "ticker", "floor", "close"]].sort_values(["ticker", "date"]).assign(
    returns = lambda df : df.groupby("ticker")["close"].pct_change(),
    log_returns_pct = lambda df : np.log(df["close"] / df.groupby("ticker")["close"].shift(1))*100
)

data = data.loc[data["ticker"].str.len()==3] # Eliminate ETF, and indeces

data["limit"] = data["floor"].map(limits)
outliers = data.loc[data["returns"].abs() > data["limit"]]
clean_df = data.drop(outliers.index) # Remove outliers
print(f"% of observations removed: {round((len(outliers)/len(data))*100, 2)}%")

# NOTE: try out different samples of stocks
pivoted_df = clean_df.pivot_table(values="returns", index="date", columns="ticker") # Pivot data for better usability
pivoted_df = pivoted_df[ticker_list].dropna()

display(pivoted_df.describe())
train_df, test_df = split_train_test(pivoted_df)

% of observations removed: 1.05%


ticker,REE,SAM,HAP
count,5951.000000,5951.000000,5951.000000
mean,0.001091,0.000699,0.000770
std,0.021411,0.023733,0.024894
min,-0.069971,-0.069999,-0.069963
25%,-0.009689,-0.011620,-0.012434
50%,0.000000,0.000000,0.000000
75%,0.011761,0.012037,0.012855
max,0.069962,0.069919,0.069927


In [3]:

class LSTMBEKKModel(nn.Module):
    
    """
    LSTM-BEKK model for multivariate volatility modeling
    """

    def __init__(
        self,
        n_assets,
        hidden_size=None,
        num_layers=3,
        dropout=0.1,
        beta=1.0
    ):
        """
        Initialize LSTM-BEKK Model
        Args: 
            n_assets: Number of stocks in the portfolio
            hidden_size: LSTM hidden size, recommended to set as equal to the number of stocks
            num_layers: Number of LSTM layers. Recommended 3-5
            dropout: Dropout rate for regularization. Recommended 0.1-0.2
            beta: Swish activation parameter
        """
        super(LSTMBEKKModel, self).__init__()

        self.n_assets = n_assets
        self.hidden_size = hidden_size or n_assets
        self.num_layers = num_layers
        self.beta = nn.Parameter(torch.tensor(beta))

        # Static lower triangular matrix C
        self.C = nn.Parameter(torch.randn(n_assets, n_assets))

        # Scalar parameters for BEKK component
        self.log_a = nn.Parameter(torch.tensor(-3.0))
        self.log_b = nn.Parameter(torch.tensor(-0.1))

        # LSTM network for dynamic component
        self.lstm = nn.LSTM(
            input_size=n_assets,
            hidden_size=self.hidden_size,
            num_layers=num_layers,
            batch_first=True, 
            dropout=dropout if num_layers > 1 else 0
        )

        # Output layer to generate lower triangular matrix element
        n_lower_triangular = n_assets * (n_assets + 1) // 2
        self.output_layer = nn.Linear(self.hidden_size, n_lower_triangular)

    def swish_activation(self, x):
        '''Swish activation function: x * sigmoid(beta * x)'''
        return x * torch.sigmoid(self.beta * x)
    
    def make_lower_triangular(self, vec):
        '''
        Convert vector to lower triangular matrix using completely functional approach
        '''
        batch_size = vec.shape[0]
        n = self.n_assets
        device = vec.device
        
        L = torch.zeros(batch_size, n, n, device=device) # Initialize lower-triangular matrix

        k = 0
        for i in range(n):
            for j in range(i + 1):
                L[:, i, j] = vec[:, k]
                k += 1

        # Create position encodings for lower triangular matrix
        positions = []
        for i in range(n):
            for j in range(i + 1):
                positions.append((i, j))
        
        # Apply Swish activation to diagonal elements
        diag_elements = torch.diagonal(L, dim1=1, dim2=2)
        active_L = L.clone()
        for i in range(n):
            active_L[:, i, i] = self.swish_activation(diag_elements[:, i])

        return active_L
    
    def get_static_C(self):
        """Get static lower triangular matrix C"""
        # Make lower triangular
        C_lower = torch.tril(self.C)
        
        # Ensure positive diagonal elements using functional approach
        diag_values = torch.diagonal(C_lower, dim1=-2, dim2=-1)
        abs_diag_values = torch.abs(diag_values) + 1e-6
        
        # Create diagonal matrix
        diag_matrix = torch.diag_embed(abs_diag_values)
        
        # Create off-diagonal part
        off_diag = C_lower - torch.diag_embed(diag_values)
        
        # Combine
        result = off_diag + diag_matrix
        
        return result
    
    def get_bekk_params(self):
        """Get positive BEKK parameters with stationarity constraint"""
        a = torch.exp(self.log_a)
        b = torch.exp(self.log_b)

        # Ensure stationarity: a + b < 1
        total = a + b
        scale_factor = torch.where(total >= 0.999, 0.998 / total, torch.tensor(1.0, device=total.device))
        
        a_scaled = a * scale_factor
        b_scaled = b * scale_factor

        return a_scaled, b_scaled

    def forward(self, returns):
        """
        Forward pass using completely functional approach
        """
        batch_size, seq_len, n_assets = returns.shape
        device = returns.device

        if seq_len == 0:
            empty_cov = torch.zeros(batch_size, 0, n_assets, n_assets, device=device)
            return empty_cov, torch.tensor(0.0, device=device)

        # Get static components
        C_static = self.get_static_C()
        CC_static = torch.mm(C_static, C_static.t())
        a, b = self.get_bekk_params()

        # LSTM forward pass
        lstm_out, _ = self.lstm(returns)
        C_t_vec = self.output_layer(lstm_out)

        # Generate dynamic matrices
        # Reshape for batch processing
        C_t_vec_reshaped = C_t_vec.view(-1, C_t_vec.shape[-1])
        C_t_matrices_flat = self.make_lower_triangular(C_t_vec_reshaped)
        C_t_matrices = C_t_matrices_flat.view(batch_size, seq_len, n_assets, n_assets)

        # Process sequence using functional approach
        all_H = []
        all_nll = []
        
        # Initial H
        H_current = CC_static.unsqueeze(0).expand(batch_size, -1, -1).contiguous()
        
        for t in range(seq_len):
            # Get current dynamic component
            C_t = C_t_matrices[:, t]
            CC_dynamic = torch.bmm(C_t, C_t.transpose(-2, -1))

            # BEKK component
            if t > 0:
                r_prev = returns[:, t-1].unsqueeze(-1)
                rr_prev = torch.bmm(r_prev, r_prev.transpose(-2, -1))
                bekk_term = a * rr_prev + b * H_current
            else:
                bekk_term = b * H_current

            # Compute new H
            H_new = CC_static.unsqueeze(0) + CC_dynamic + bekk_term
            
            # Add regularization
            reg_term = torch.eye(n_assets, device=device) * 1e-6
            H_new = H_new + reg_term.unsqueeze(0)
            
            all_H.append(H_new)

            # Compute likelihood
            try:
                L = torch.linalg.cholesky(H_new)
                log_det = 2 * torch.sum(torch.log(torch.diagonal(L, dim1=-2, dim2=-1)), dim=-1)
                
                r_t = returns[:, t].unsqueeze(-1)
                y = torch.triangular_solve(r_t, L, upper=False)[0]
                quad_form = torch.sum(y ** 2, dim=(-2, -1))
                
                nll_t = 0.5 * (log_det + quad_form)
                all_nll.append(torch.mean(nll_t))
                
            except Exception as e:
                print(f"Cholesky failed at t={t}: {e}")
                all_nll.append(torch.tensor(1e6, device=device))

            # Update H_current - create completely new tensor
            H_current = H_new.clone().detach()

        # Combine results
        covariance_matrices = torch.stack(all_H, dim=1)
        total_nll = sum(all_nll) if all_nll else torch.tensor(0.0, device=device)
        
        return covariance_matrices, total_nll

    def forecast(self, past_returns, n_steps=20, sampling=False):
        """
        Multi-step ahead forecast
        Args:
            past_returns: Tensor (1, seq_len, n_assets)
            n_steps: number of steps ahead
            sampling: if True, sample future returns, else assume zero mean
        Returns:
            forecasts: list of covariance matrices for n_steps
        """

        self.eval()
        device = past_returns.device
        with torch.no_grad():
            # Run LSTM to get dynamic component
            lstm_out, (h_n, c_n) = self.lstm(past_returns)
            hidden = lstm_out[:, -1:] # Last step hidden state

            # Get static components
            C_static = self.get_static_C()
            CC_static = torch.mm(C_static, C_static.t())
            a, b = self.get_bekk_params()

            # Last observed covariance
            covariances, _ = self.forward(past_returns)
            H_current = covariances[:, -1]

            # Last observed return
            r_prev = past_returns[:, -1]

            forecasts = []
            for step in range(n_steps):
                # Dynamic matrix from hidden state
                C_vec = self.output_layer(hidden).view(-1, self.output_layer.out_features)
                C_mat = self.make_lower_triangular(C_vec)[0]
                CC_dynamic = C_mat @ C_mat.T

                rr_prev = r_prev @ r_prev.T
                H_new = CC_static + CC_dynamic + a * rr_prev + b * H_current
                H_new = H_new + torch.eye(self.n_assets, device=device) * 1e-6

                forecasts.append(H_new)

                # Update for next iteration
                H_current = H_new.clone()
                if sampling:
                    r_prev = torch.distributions.MultivariateNormal(
                        loc=torch.zeros(self.n_assets, device=device), covariance_matrix=H_new
                    ).sample()
                else:
                    r_prev = torch.zeros(self.n_assets, device=device)

                # Evolve LSTM hidden state with zero input
                zero_input = torch.zeros(1, 1, self.n_assets, device=device)
                hidden, (h_n, c_n) = self.lstm(zero_input, (h_n, c_n))

            return forecasts

class ReturnDataset(Dataset):
    """Dataset class for multivariate return data"""
    def __init__(self, returns, seq_len=50):
        self.returns = torch.tensor(returns, dtype=torch.float32)
        self.seq_len = seq_len
        self.T, self.n_assets = self.returns.shape

    def __len__(self):
        return max(0, self.T - self.seq_len + 1)
    
    def __getitem__(self, index):
        return self.returns[index:index + self.seq_len]


class LSTMBEKKTrainer:
    """Trainer class for LSTM-BEKK Model"""
    
    def __init__(self, model, learning_rate=0.001, weight_decay=1e-5):
        self.model = model
        self.optimizer = optim.RMSprop(
            model.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
            eps=1e-8
        )
        self.scheduler = optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer,
            mode='min',
            factor=0.5,
            patience=10
        )

    def train_epoch(self, train_loader):
        """Train for one epoch"""

        self.model.train()
        total_loss = 0.0
        num_batches = 0

        for batch_idx, batch_returns in enumerate(train_loader):
            batch_returns = batch_returns.to(next(self.model.parameters()).device)

            # Zero gradients
            self.optimizer.zero_grad()

            try:
                # Forward pass
                _, loss = self.model(batch_returns)

                # Regularization
                reg_loss = torch.tensor(0.0, device=loss.device)
                for param in self.model.parameters():
                    reg_loss = reg_loss + torch.sum(torch.abs(param))
                
                total_loss_batch = loss + 1e-6 * reg_loss
                
                # Backward pass
                total_loss_batch.backward()

                # Gradient clipping
                torch.nn.utils.clip_grad_norm_(self.model.parameters(), max_norm=1.0)

                # Optimizer step
                self.optimizer.step()

                total_loss += loss.item()
                num_batches += 1

            except Exception as error:
                print(f"Error in training batch {batch_idx}: {error}")
                import traceback
                traceback.print_exc()
                continue
        
        return total_loss / max(num_batches, 1)
    
    def validate(self, val_loader):
        """Validate the model"""
        self.model.eval()
        total_loss = 0.0
        num_batches = 0

        with torch.no_grad():
            for batch_returns in val_loader:
                batch_returns = batch_returns.to(next(self.model.parameters()).device)

                try:
                    _, loss = self.model(batch_returns)
                    total_loss += loss.item()
                    num_batches += 1
                except Exception as e:
                    print(f"Error in validation batch: {e}")
                    continue
            
        return total_loss / max(num_batches, 1)

    def train(self, train_loader, val_loader, epochs=100, patience=20):
        """Train the LSTM-BEKK model"""
        
        best_val_loss = float("inf")
        patience_counter = 0
        train_losses = []
        val_losses = []

        print("Starting LSTM-BEKK training...")
        a_param, b_param = self.model.get_bekk_params()
        print(f"Model parameters: a = {a_param:.4f}, b = {b_param:.4f}")

        for epoch in range(epochs):
            # Training
            train_loss = self.train_epoch(train_loader)
            train_losses.append(train_loss)

            # Validation
            val_loss = self.validate(val_loader)
            val_losses.append(val_loss)

            # Learning rate scheduling
            self.scheduler.step(val_loss)

            print(f"Epoch {epoch + 1}/{epochs}: Train loss = {train_loss:.6f}; Val loss = {val_loss:.6f}")

            # Early stopping
            if val_loss < best_val_loss:
                best_val_loss = val_loss
                patience_counter = 0
                torch.save(self.model.state_dict(), "best_lstm_bekk_model.pth")
            else:
                patience_counter += 1

            if patience_counter >= patience:
                print(f"Early stopping at epoch {epoch + 1}")
                break

        # Load best model
        self.model.load_state_dict(torch.load('best_lstm_bekk_model.pth'))
        print("Training completed!")

        return train_losses, val_losses
    
    
def evaluate_model(model, test_loader):
    """Evaluate model on test data"""
    model.eval()
    total_nll = 0.0
    num_batches = 0

    with torch.no_grad():
        for batch_returns in test_loader:
            batch_returns = batch_returns.to(next(model.parameters()).device)

            try:
                _, nll = model(batch_returns)
                total_nll += nll.item()
                num_batches += 1 
            except Exception as e:
                print(f"Error in evaluation: {e}")
                continue
                
    avg_nll = total_nll / max(num_batches, 1)
    return avg_nll


In [4]:
# TRAIN MODEL


torch.autograd.set_detect_anomaly(True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
seq_len = 50
batch_size = 32

sample_df = pivoted_df.values
n_assets = sample_df.shape[1]

train_returns, test_returns = train_test_split(sample_df, test_size=0.2, shuffle=False)
train_returns, val_returns = train_test_split(train_returns, test_size=0.2, shuffle=False)

# Demean returns
train_mean = np.mean(train_returns)
dm_train_returns = train_returns - train_mean
dm_val_returns = val_returns - train_mean
dm_test_returns = test_returns - train_mean


print(f"Data shapes: Train = {train_returns.shape}, Val = {val_returns.shape}, Test = {test_returns.shape}")

train_dataset = ReturnDataset(dm_train_returns, seq_len=seq_len)
val_dataset = ReturnDataset(dm_val_returns, seq_len=seq_len)
test_dataset = ReturnDataset(dm_test_returns, seq_len=seq_len)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Initialize model
print("Initializing LSTM-BEKK Model...")
model = LSTMBEKKModel(
    n_assets=n_assets,
    hidden_size=n_assets,
    num_layers=3,
    dropout=0.1
).to(device)

print(f"Model parameters: {sum(p.numel() for p in model.parameters())} total parameters")

# Initialize trainer
trainer = LSTMBEKKTrainer(model, learning_rate=0.001)

# Train model
train_losses, val_losses = trainer.train(
    train_loader, val_loader, epochs=15, patience=15
)

avg_nll_test = evaluate_model(model, test_loader)

Using device: cpu
Data shapes: Train = (3808, 3), Val = (952, 3), Test = (1191, 3)
Initializing LSTM-BEKK Model...
Model parameters: 324 total parameters
Starting LSTM-BEKK training...
Model parameters: a = 0.0498, b = 0.9048
Epoch 1/15: Train loss = 52.338918; Val loss = 4.958982
Epoch 2/15: Train loss = -34.428159; Val loss = -78.115375
Epoch 3/15: Train loss = -136.212420; Val loss = -174.684735
Epoch 4/15: Train loss = -191.775443; Val loss = -203.705648
Epoch 5/15: Train loss = -225.879457; Val loss = -243.049828
Epoch 6/15: Train loss = -296.160781; Val loss = -339.343265
Epoch 7/15: Train loss = -338.480451; Val loss = -344.770595
Epoch 8/15: Train loss = -346.218009; Val loss = -353.463518
Epoch 9/15: Train loss = -356.301875; Val loss = -363.322481
Epoch 10/15: Train loss = -368.178121; Val loss = -376.967787
Epoch 11/15: Train loss = -381.513165; Val loss = -392.540821
Epoch 12/15: Train loss = -398.984195; Val loss = -414.530417
Epoch 13/15: Train loss = -426.990893; Val los

In [9]:
# Save the trained LSTM-BEKK model to a file
torch.save(model.state_dict(), os.path.join("lstm_results", f"lstm_bekk_model_{batch_size}BS_{15}epochs_{seq_len}LSTMSL_{n_assets}A.pth"))

In [5]:
# Load the trained LSTM-BEKK model from the file
model_path = os.path.join("lstm_results", "lstm_bekk_model_15epochs_50LSTMSL_3A.pth")
model.load_state_dict(torch.load(model_path, map_location=device))
# model.eval()  # Set the model to evaluation mode

<All keys matched successfully>

In [7]:
# FORECAST
dm_train_r_ts = torch.tensor(dm_train_returns, dtype=torch.float32).unsqueeze(0)
forecast = model.forecast(dm_train_r_ts, n_steps=30, sampling=True)

In [8]:
forecast

[tensor([[[2.0044e-04, 5.6105e-05, 9.2301e-05],
          [5.6105e-05, 1.9451e-04, 1.4176e-04],
          [9.2301e-05, 1.4176e-04, 4.5618e-04]]]),
 tensor([[[1.7335e-04, 4.4151e-05, 8.0861e-05],
          [4.4151e-05, 1.7986e-04, 1.2731e-04],
          [8.0861e-05, 1.2731e-04, 4.4145e-04]]]),
 tensor([[[0.0003, 0.0002, 0.0002],
          [0.0002, 0.0003, 0.0002],
          [0.0002, 0.0002, 0.0006]]]),
 tensor([[[0.0002, 0.0001, 0.0002],
          [0.0001, 0.0003, 0.0002],
          [0.0002, 0.0002, 0.0005]]]),
 tensor([[[0.0003, 0.0002, 0.0002],
          [0.0002, 0.0003, 0.0003],
          [0.0002, 0.0003, 0.0006]]]),
 tensor([[[0.0003, 0.0002, 0.0002],
          [0.0002, 0.0003, 0.0003],
          [0.0002, 0.0003, 0.0006]]]),
 tensor([[[0.0005, 0.0004, 0.0004],
          [0.0004, 0.0005, 0.0004],
          [0.0004, 0.0004, 0.0008]]]),
 tensor([[[0.0003, 0.0002, 0.0002],
          [0.0002, 0.0003, 0.0003],
          [0.0002, 0.0003, 0.0006]]]),
 tensor([[[1.9673e-04, 7.6171e-05, 1.131

### Creating loop for evaluation

In [ ]:
# Test loop for evaluating model and refit every n days
### #Latest update

torch.autograd.set_detect_anomaly(True)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

batch_size = 32
n_epochs = 15
learning_rate = 0.001

sample_df = pivoted_df.values
n_assets = sample_df.shape[1]

# Split train, test set
train_returns, test_returns = train_test_split(sample_df, test_size=1 - 0.958, shuffle=False)

horizon = 10
lookback = len(train_returns)
test_len = len(test_returns)
lstm_seq_len = 50


lstm_pred_covs = []

dm_test_r = test_returns - train_mean

for step in tqdm(range(0, test_len, horizon)):

    start_index = (len(train_returns) - lookback) + step
    end_index = len(train_returns) + step
    window = sample_df[start_index:end_index]

    # split train and eval returns
    train, eval = train_test_split(window, test_size=0.2, shuffle=False)

    # Demean returns
    train_mean = np.mean(train)
    dm_train_r = train - train_mean
    dm_eval_r = eval - train_mean

    train_dataset = ReturnDataset(dm_train_r, seq_len=lstm_seq_len)
    eval_dataset = ReturnDataset(dm_eval_r, seq_len=lstm_seq_len)
    # test_dataset = ReturnDataset(dm_test_r, seqe_len=lstm_seq_len)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
    eval_loader = DataLoader(eval_dataset, batch_size=batch_size, shuffle=False)

    model = LSTMBEKKModel(
        n_assets=n_assets,
        hidden_size=n_assets,
        num_layers=3,
        dropout=0.1
    ).to(device)

    trainer = LSTMBEKKTrainer(model, learning_rate=learning_rate)

    train_losses, val_losses = trainer.train(
        train_loader, val_loader, epochs=n_epochs, patience=15
    )

    window_ts = torch.tensor(window, dtype=torch.float32).unsqueeze(0).to(device)
    forecast = model.forecast(window_ts, n_steps=horizon, sampling=True)

    lstm_pred_covs.append(forecast)


Using device: cpu


  0%|          | 0/25 [00:00<?, ?it/s]

Starting LSTM-BEKK training...
Model parameters: a = 0.0498, b = 0.9048
Epoch 1/15: Train loss = 16.657156; Val loss = -52.384547
Epoch 2/15: Train loss = -120.957445; Val loss = -169.773883
Epoch 3/15: Train loss = -196.513723; Val loss = -246.919684
Epoch 4/15: Train loss = -294.088156; Val loss = -301.923270
Epoch 5/15: Train loss = -312.071819; Val loss = -309.259041
Epoch 6/15: Train loss = -319.705701; Val loss = -314.367318
Epoch 7/15: Train loss = -327.167510; Val loss = -322.257385
Epoch 8/15: Train loss = -335.855276; Val loss = -330.417613
Epoch 9/15: Train loss = -342.770116; Val loss = -339.108547
Epoch 10/15: Train loss = -352.327990; Val loss = -347.871523
Epoch 11/15: Train loss = -360.935613; Val loss = -358.231562
Epoch 12/15: Train loss = -373.856812; Val loss = -370.681641
Epoch 13/15: Train loss = -387.834369; Val loss = -387.346669
Epoch 14/15: Train loss = -407.092945; Val loss = -413.109421
Epoch 15/15: Train loss = -445.046290; Val loss = -485.203627
Training c

  0%|          | 0/25 [34:57<?, ?it/s]


In [38]:
pred = np.concatenate(np.array(model.forecast(window_ts, n_steps=10, sampling=True)), axis=0)

In [19]:
realized_cov = get_rolling_realized_covariance(sample_df, window_size=len(train_returns))
actual_covs = realized_cov[-len(test_returns):]

In [40]:
lstm_frob = np.mean([frobenius_loss(t, p) for t, p in zip(actual_covs, pred[:len(actual_covs)])])

In [ ]:
with open(os.path.join("lstm_results", f"test_lstm_frob_{lookback}SL_{lstm_seq_len}LSTSQ_{n_assets}A_{horizon}S.pkl"), "wb") as f:
    

5701

In [33]:
np.mean([frobenius_loss(true, pred) for true, pred in zip(actual_covs[:10], np_forecasts)])

3.319779824421665e-07

==============================

In [ ]:

# Start loop from here
train_returns, val_returns = train_test_split(train_returns, test_size=0.2, shuffle=False)

# Demean returns
train_mean = np.mean(train_returns)
dm_train_returns = train_returns - train_mean
dm_val_returns = val_returns - train_mean
dm_test_returns = test_returns - train_mean


print(f"Data shapes: Train = {train_returns.shape}, Val = {val_returns.shape}, Test = {test_returns.shape}")

train_dataset = ReturnDataset(dm_train_returns, seq_len=seq_len)
val_dataset = ReturnDataset(dm_val_returns, seq_len=seq_len)
test_dataset = ReturnDataset(dm_test_returns, seq_len=seq_len)

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Initialize model
print("Initializing LSTM-BEKK Model...")
model = LSTMBEKKModel(
    n_assets=n_assets,
    hidden_size=n_assets,
    num_layers=3,
    dropout=0.1
).to(device)

print(f"Model parameters: {sum(p.numel() for p in model.parameters())} total parameters")

# Initialize trainer
trainer = LSTMBEKKTrainer(model, learning_rate=learning_rate)

# Train model
train_losses, val_losses = trainer.train(
    train_loader, val_loader, epochs=n_epochs, patience=15
)

# avg_nll_test = evaluate_model(model, test_loader)

In [9]:
# Suppose test_returns is shape [T, n_assets]

horizon = 1
test_len = dm_test_returns.shape[0]
seq_len = 1000
dm_full_returns = np.concat([dm_train_returns, dm_test_returns])
lstm_pred_covs = []


In [ ]:
dm_full_returns.shape

(4999, 3)

In [ ]:

for step in tqdm(range(test_len)):

    start_index = len(dm_train_returns) - seq_len + step
    end_index = len(dm_train_returns) + step
    window = dm_full_returns[start_index:end_index] 

    window = torch.tensor(window, dtype=torch.float32).unsqueeze(0)
    forecasts = model.forecast(window, n_steps=horizon, sampling=True)
    lstm_pred_covs.append(forecasts)


In [70]:

past_window = dm_train_returns[-seq_len:]  # shape (seq_len, n_assets)
past_window = torch.tensor(past_window, dtype=torch.float32).unsqueeze(0)  # shape (1, seq_len, n_assets)
forecasts = model.forecast(past_window, n_steps=forecast_steps, sampling=True)

act_covs = []
for i in range(forecast_steps):
    returns_t = dm_test_returns[i]
    realized_cov = np.outer(returns_t, returns_t)
    act_covs.append(realized_cov)

lstm_frob = np.mean([frobenius_loss(true, pred.squeeze(0)) for true, pred in zip(np.array(act_covs), np.array(forecasts))])

In [ ]:
np.float64(1.0066058055254416e-05)

In [71]:
lstm_frob

np.float64(9.158142197269257e-06)

In [65]:
import pickle
with open(os.path.join("lstm_results", "lstm_frob_3A_TS.pkl"), "wb") as f:
    pickle.dump(lstm_frob, f)