In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from datetime import datetime
import os
import torch
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import matplotlib.pyplot as plt
import numpy as np
import pickle
import importlib
from sklearn.model_selection import train_test_split

from MODELS import LSTM_BEKK_MODEL, BEKK_GARCH_MODEL, DCC_GARCH_MODEL, SVR_MODEL
from functions import *
from evaluate import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Data cleaning:

Some close price is inappropriate, which lead to over the price fluctuation limit set by the exchange, fixed this by removing the observations that have day-to-day change over the exchange limit.

In [21]:
# ticker_list = ['REE', 'SAM', 'HAP', 'GMD', 'GIL', 'TMS', 'SAV', 'DHA', 'MHC', 'HAS'] # 10 stocks with the most observations
ticker_list = ['REE', 'SAM', 'HAP'] # 3 stocks with the most observations
limits = {
    'hose':0.07,
    'hnx':0.1,
    'upcom':0.15
}

# Parameters

horizon = 10
seq_len = 1000
train_pct = 0.958


In [4]:
# Read and merge into 1 dataset

if "stock_data.csv" in os.listdir("data"):
    merged_df = pd.read_csv(
        os.path.join("data", "stock_data.csv"),
        index_col=None
    ).assign(
        date = lambda df : pd.to_datetime(df["date"])
    )
else:
    # Read and merge data
    hnx = pd.read_csv(os.path.join("data", "CafeF.HNX.Upto31.07.2025.csv")).assign(
        floor = "hnx"
    )
    hsx = pd.read_csv(os.path.join("data", "CafeF.HSX.Upto31.07.2025.csv")).assign(
        floor = "hose"
    )
    upcom = pd.read_csv(os.path.join("data", "CafeF.UPCOM.Upto31.07.2025.csv")).assign(
        floor = "upcom"
    )
    indexes = pd.read_csv(os.path.join("data", "CafeF.INDEX.Upto06.08.2025.csv")).assign(
        floor = "index"
    )

    # Rename columns
    hnx, hsx, upcom, indexes = [
        df.rename(columns={
            "<Ticker>":"ticker",
            "<DTYYYYMMDD>":"date",
            "<Open>":"open",
            "<High>":"high",
            "<Low>":"low",
            "<Close>":"close",
            "<Volume>":"volume"
        }) for df in [hnx, hsx, upcom, indexes]
    ]
        
    # Merge and clean data
    # UPCOM has missing tickers for some reason
    merged_df = pd.concat(
        [hnx, hsx, upcom, indexes],
        axis=0
    ).reset_index(drop=True).dropna(subset="ticker")\
    .assign(
        date=lambda df : df["date"].astype(str).apply(lambda x: datetime.strptime(x, "%Y%m%d").date())
    )
    merged_df.to_csv(
        os.path.join("data", "stock_data.csv"),
        index=False
    ) # Save merged data to save time in future runs


# Data cleaning and merging

data = merged_df.sort_values(["ticker", "date"]).assign(
    returns = lambda df : df.groupby("ticker")["close"].pct_change(),
    log_returns_pct = lambda df : np.log(df["close"] / df.groupby("ticker")["close"].shift(1))*100
)

data = data.loc[data["ticker"].str.len()==3] # Eliminate ETF, and indeces

data["limit"] = data["floor"].map(limits)
outliers = data.loc[data["returns"].abs() > data["limit"]]
clean_df = data.drop(outliers.index) # Remove outliers
print(f"% of observations removed: {round((len(outliers)/len(data))*100, 2)}%")

pivoted_data = clean_df.pivot_table(
    columns="ticker", 
    values=["open", "high", "low", "close", "returns"], 
    index="date"
)
pivoted_data.columns = pivoted_data.columns.swaplevel(0, 1)
pivoted_data = pivoted_data.sort_index(axis=1, level=0)
pivoted_data = pivoted_data.loc[:, pivoted_data.columns.get_level_values(0).isin(ticker_list)]
pivoted_data = pivoted_data.dropna() # Drop NA

data_returns = pivoted_data.loc[:, pivoted_data.columns.get_level_values(1) == "returns"]
data_hl = pivoted_data.loc[:, pivoted_data.columns.get_level_values(1).isin(["high", 'low'])]

display(data_returns.describe())
train_df, test_df = split_train_test(data_returns, train_ratio = train_pct)
train_df_hl, test_df_hl = split_train_test(data_hl, train_ratio=train_pct)

# Demean returns
train_mean = train_df.mean()
dm_train_df = train_df - train_mean
dm_test_df = test_df - train_mean
test_len = dm_test_df.shape[0]

print(f"""
Total data: {len(data_returns)} observations
Train set: {len(dm_train_df)} observations
Test set: {len(dm_test_df)} observations
""")

% of observations removed: 1.05%


ticker,HAP,REE,SAM
,returns,returns,returns
count,5951.000000,5951.000000,5951.000000
mean,0.000770,0.001091,0.000699
std,0.024894,0.021411,0.023733
min,-0.069963,-0.069971,-0.069999
25%,-0.012434,-0.009689,-0.011620
50%,0.000000,0.000000,0.000000
75%,0.012855,0.011761,0.012037
max,0.069927,0.069962,0.069919



Total data: 5951 observations
Train set: 5701 observations
Test set: 251 observations



In [5]:
realized_cov = get_rolling_realized_covariance(data_returns.values, window_size=1000)
actual_covs = realized_cov[-len(dm_test_df):]

Why demean the returns?

Volatility models like BEKK aim to model the covariance structure, not the mean.
By removing the mean from the return, it tells the model to focus on modeling volatility clustering and correlations, as well as preventing the mean return from contaminating the volatility dynamics

The mean from the training set will be used to demean the test set to simulate real world situation.

What's the differences between using static mean and moving average?

### ARCH
An ARCH model is used to predict volatility at a future time step, with the parameter $q$ as the number of lag squared residual error to include in the model 
ARCH uses returns or residuals as volatility shocks.

In [16]:
from arch import arch_model

garch = arch_model(pivoted_df["REE"]*100, vol="ARCH")
garch.fit()

Iteration:      1,   Func. Count:      5,   Neg. LLF: 129357.59275774604
Iteration:      2,   Func. Count:     12,   Neg. LLF: 15382.891572734194
Iteration:      3,   Func. Count:     19,   Neg. LLF: 13170.123600844268
Iteration:      4,   Func. Count:     24,   Neg. LLF: 12577.94370714599
Iteration:      5,   Func. Count:     28,   Neg. LLF: 12577.939139618782
Iteration:      6,   Func. Count:     32,   Neg. LLF: 12577.938832634314
Iteration:      7,   Func. Count:     36,   Neg. LLF: 12577.938830220966
Iteration:      8,   Func. Count:     39,   Neg. LLF: 12577.938830221014
Optimization terminated successfully    (Exit mode 0)
            Current function value: 12577.938830220966
            Iterations: 8
            Function evaluations: 39
            Gradient evaluations: 8


                      Constant Mean - ARCH Model Results                      
Dep. Variable:                    REE   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                       ARCH   Log-Likelihood:               -12577.9
Distribution:                  Normal   AIC:                           25161.9
Method:            Maximum Likelihood   BIC:                           25182.0
                                        No. Observations:                 5951
Date:                Wed, Aug 27 2025   Df Residuals:                     5950
Time:                        10:10:31   Df Model:                            1
                                Mean Model                                
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.0930  2.486e-02      3.740  1.837e-04 [4.426e-0

### GARCH

In [ ]:
from arch import arch_model

garch = arch_model(pivoted_df["REE"]*100, vol="GARCH")
garch.fit()

Iteration:      1,   Func. Count:      6,   Neg. LLF: 6841595578418.32
Iteration:      2,   Func. Count:     15,   Neg. LLF: 6411162190.4786215
Iteration:      3,   Func. Count:     23,   Neg. LLF: 14540.272691777205
Iteration:      4,   Func. Count:     30,   Neg. LLF: 12675.511071518553
Iteration:      5,   Func. Count:     38,   Neg. LLF: 12163.288926570278
Iteration:      6,   Func. Count:     44,   Neg. LLF: 12162.193236000765
Iteration:      7,   Func. Count:     49,   Neg. LLF: 12162.192674535536
Iteration:      8,   Func. Count:     54,   Neg. LLF: 12162.192667947853
Iteration:      9,   Func. Count:     59,   Neg. LLF: 12162.192667437183
Optimization terminated successfully    (Exit mode 0)
            Current function value: 12162.192667437183
            Iterations: 9
            Function evaluations: 59
            Gradient evaluations: 9


                     Constant Mean - GARCH Model Results                      
Dep. Variable:                    REE   R-squared:                       0.000
Mean Model:             Constant Mean   Adj. R-squared:                  0.000
Vol Model:                      GARCH   Log-Likelihood:               -12162.2
Distribution:                  Normal   AIC:                           24332.4
Method:            Maximum Likelihood   BIC:                           24359.2
                                        No. Observations:                 5951
Date:                Wed, Aug 27 2025   Df Residuals:                     5950
Time:                        10:10:31   Df Model:                            1
                                Mean Model                                
                 coef    std err          t      P>|t|    95.0% Conf. Int.
--------------------------------------------------------------------------
mu             0.0747  2.140e-02      3.493  4.770e-04 [3.281e-0

# BEKK-GARCH

$$H_t=C'C+A'\epsilon_{t-1}\epsilon_{t-1}'A+B'H_{t-1}B$$

- $H_t$: n_assets x n_assets conditional covariance matrix
- $C$: Lower triangular matrix to ensure positive definteness
- $A$: Captures the effect of past shocks (ARCH)
- $B$: Captures the persistence (GARCH)
- $\epsilon_{t-1}$: Vector of past residuals (demeaned returns)

### Usage
- Used for small dimensions of 2-3 assets.
- Contagion studies, volatility spillovers.

### Advantages
- Guarantees positive definite covariance matrices
- Captures spillover effects across assets
- More flexible in modeling asymmetric dependencies

### Disadvantages
- Computationally heavy, parameter explosion: for $N$ assets, get ~$N^2$ parameters
- Harder to estimate high-dimensional data
- May overfit with limited data

Since the model suffers from the curse of dimensionality, so I can only sample 3 stocks, at around 1000 days windows. This should be tuned later

In [ ]:
# # Run model
# if "bekk_results.pkl" in os.listdir("bekk_params"):
#     with open(os.path.join("bekk_params", "bekk_results.pkl"), "rb") as f:
#         bekk = pickle.load(f)
#     with open(os.path.join("bekk_params", "bekk_A.pkl"), "rb") as f:
#         A = pickle.load(f)
#     with open(os.path.join("bekk_params", "bekk_B.pkl"), "rb") as f:
#         B = pickle.load(f)
#     with open(os.path.join("bekk_params", "bekk_C.pkl"), "rb") as f:
#         C = pickle.load(f) 
# else:
#     # Fit BEKK-GARCH model, dimensions is greately reduced as this model suffers from curse of dimensionality
#     sub_dm_train_df = dm_train_df.tail(1000)
#     C, A, B, bekk = BEKK_GARCH_MODEL.fit_bekk(sub_dm_train_df.values) 
    
#     # Save covariance matrix and model parameters
#     with open(os.path.join("bekk_params", "bekk_results.pkl"), "wb") as f:
#         pickle.dump(bekk, f)
#     with open(os.path.join("bekk_params", "bekk_C.pkl"), "wb") as f:
#         pickle.dump(C, f)
#     with open(os.path.join("bekk_params", "bekk_A.pkl"), "wb") as f:
#         pickle.dump(A, f)
#     with open(os.path.join("bekk_params", "bekk_B.pkl"), "wb") as f:
#         pickle.dump(B, f)

# # Get BEKK-GARCH fitted covariance        
# cov_matrix = BEKK_GARCH_MODEL.bekk_fitted_covariances(bekk.x, returns=sub_dm_train_df.values)

In [51]:
# Forecast

bekk_pred_covs = []

np.random.seed(42)
n_assets = data_returns.shape[1]
nC = n_assets * (n_assets+1) // 2
n_params = nC + 2*n_assets*n_assets
x0 = 0.05 * np.random.randn(n_params) # initialize first value

for step in tqdm(range(0, test_len, horizon)):
    
    start_index = len(dm_train_df) - seq_len + step
    end_index = len(dm_train_df) + step
    window = data_returns.iloc[start_index:end_index]

    C, A, B, bekk = BEKK_GARCH_MODEL.fit_bekk(window.values, x0=x0)

    forecasts = BEKK_GARCH_MODEL.bekk_forecast(
        C, A, B,
        window.values, 
        horizon=horizon
    )

    x0 = bekk.x

    bekk_pred_covs.append(np.array(forecasts))

100%|██████████| 26/26 [1:23:00<00:00, 191.57s/it]


In [22]:
with open(os.path.join("bekk_results", f"bekk_pred_covs_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), 'wb') as f:
    pickle.dump(bekk_pred_covs, f)

NameError: name 'bekk_pred_covs' is not defined

In [ ]:
bekk_pred_covs_eval = np.concatenate(bekk_pred_covs, axis=0)
bekk_pred_covs_eval = bekk_pred_covs_eval[:len(actual_covs)]

In [59]:
bekk_frob = np.mean([
    frobenius_loss(true, pred) for true, pred in zip(actual_covs, np.array(bekk_pred_covs_eval))
])
bekk_frob

np.float64(1.2596305131679146e+20)

In [ ]:
with open(os.path.join("bekk_results", f"bekk_frob_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(bekk_frob, f)

# DCC-GARCH
Is a two-step model:
1. Estimate univariate GARCH for each asset's variance

$$h_{i,t}=\omega_i + \alpha_i \epsilon_{i,t-1}^2+\beta_i h_{i,t-1}$$

2. Model the correlations dynamically:

$$H_t=D_tR_tD_t$$

With:
- $D_t=diag(\sqrt{h_{1,t}},...,\sqrt{h_{N,t}})$: matrix of standard deviations
- $R_t$: dynamic correlation matrix, updated via:
$$Q_t=(1-\alpha-\beta)\overline{Q}+\alpha \epsilon_{t-1} \epsilon_{t-1}' + \beta Q_{t-1}$$
$$R_t=diag(Q_t)^{-\frac{1}{2}} Q_t diag(Q_t)^{-\frac{1}{2}}$$
- $\overline{Q}$: Unconditional correlation matrix

### Usage
- Designed for high-dimensional portfolios (10-100 assets)
- Used for correlation dynamics, portfolio optimization, hedging

### Advantages
- Computationally efficient, espically in large dimensions
- Decouples volatility (diagonal part) and correlation (off-diagonal part)
- Easier to interpret dynamic correlation structure
- Widely used in epirical finance

### Disadvantages
- Less flexible than BEKK
- Correlations may be biased if univariage GARCH models are misspecified
- Does not directly capture cross-variance spillovers


In [ ]:
# Forecast

def train_dcc(dm_train_df):
    
    dm_train_df = dm_train_df.astype(float)
    h_mat, eps_mat, garch_params = DCC_GARCH_MODEL.fit_univariate_garch(dm_train_df) # Fit univariate GARCH for each stock
    dcc = DCC_GARCH_MODEL.fit_dcc(eps_mat) # Fit DCC(1,1) on standardized residuals
    cov_matrix = DCC_GARCH_MODEL.build_covmatrix(h_mat, dcc["Rt"]) # Get full list of conditional covariance

    return h_mat, eps_mat, garch_params, dcc, cov_matrix

dcc_pred_covs = []

for step in tqdm(range(0, test_len, horizon)):

    start_index = len(dm_train_df) - seq_len + step
    end_index = len(dm_train_df) + step
    window = data_returns.iloc[start_index:end_index]

    h_mat, eps_mat, garch_params, dcc, cov_matrix = train_dcc(window)

    forecasts, _, _, _ = DCC_GARCH_MODEL.forecast_dcc_multi_step(
        r_last=window.iloc[-1].to_numpy(),
        h_last=h_mat[-1],
        garch_params=garch_params,
        eps_last=eps_mat[-1],
        Q_last=dcc["Qt"][-1],
        dcc_params=dcc,
        S=dcc["S"],
        horizon=horizon
    )

    dcc_pred_covs.append(forecasts)


In [ ]:
with open(os.path.join("dcc_results", f"dcc_pred_covs_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(dcc_pred_covs, f)
    
dcc_pred_covs_eval = np.concatenate(dcc_pred_covs, axis=0)
dcc_pred_covs_eval = (dcc_pred_covs_eval[:len(actual_covs)])

In [ ]:
dcc_frob = np.mean([frobenius_loss(true, pred) for true, pred in zip(np.array(actual_covs), np.array(dcc_pred_covs_eval))])

with open(os.path.join("dcc_results", f"dcc_frob_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(dcc_frob, f)

np.float64(1.5701055575831849e-06)

# Supported Vector Regression - SVR

Core concept: Use regression model to forecast Cholesky entries, then reconstruct the covarianec matrix from the Cholesky factor

Steps:

1. Calculate NxN range-based (using High and Low price instead of Close)
2. Train the autoregressive SVR model on the entries of the Cholesky decomposition
3. Forecast Cholesky entries to build the Cholesky factors
4. Use the forecasted Cholesky factors to reconstruct the covariance matrix

In [91]:
lags = 45
svr_pred_covs = []

for step in tqdm(range(0, test_len, horizon)):

    start_index = len(dm_train_df) - seq_len + step
    end_index = len(dm_train_df) + step
    window = data_returns.iloc[start_index:end_index]
    window_hl = data_hl.iloc[start_index:end_index]

    pred_cov = SVR_MODEL.svr_model_forecast(
        train_data=window_hl,
        horizon=horizon,
        lags=lags   
    )
    svr_pred_covs.append(pred_cov)

100%|██████████| 26/26 [01:09<00:00,  2.69s/it]


In [ ]:
with open(os.path.join("svr_results", f"svr_pred_covs_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(svr_pred_covs, f)

svr_pred_covs_eval = np.concatenate(svr_pred_covs, axis=0)
svr_pred_covs_eval = svr_pred_covs_eval[:len(actual_covs)]

In [98]:
svr_frob = np.mean([frobenius_loss(T, P) for T, P in zip(actual_covs, svr_pred_covs_eval)])
svr_frob

np.float64(1.29697838498503e-06)

In [ ]:
with open(os.path.join("svr_results", f"svr_frob_{lags}L_{seq_len}SL_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(svr_frob, f)

# LSTM-BEKK

$$H_t = C'C + C_t'C_t + a r_{t-1} r_{t-1}' + b H_{t-1}$$


$C_t$ is dynamically updated through an LSTM network $\overline{C_t}=LSTM(h_{t-1}, r_{t-1})$, with $C_t=LowerTriangular(\overline{C_t})$

In [19]:
len(train_set)

5701

In [23]:
# Test run
torch.autograd.set_detect_anomaly(True)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")
batch_size = 32

sample_df = data_returns.values * 100
n_assets = sample_df.shape[1]

train_set, test_returns = train_test_split(sample_df, test_size=(1 - train_pct), shuffle=False)

lstm_pred_covs = []
nll_tests = []
lstm_seq_len = 50
seq_len = 5700

for step in tqdm(range(0, test_len, horizon)):
    
    start_index = len(train_set) - seq_len + step
    end_index = len(train_set) + step
    window = sample_df[start_index:end_index]

    train_returns, val_returns = train_test_split(window, test_size=0.2, shuffle=False)

    # Demean returns
    train_mean = np.mean(train_returns)
    dm_train_returns = train_returns - train_mean
    dm_val_returns = val_returns - train_mean
    dm_test_returns = test_returns - train_mean


    print(f"Data shapes: Train = {train_returns.shape}, Val = {val_returns.shape}, Test = {test_returns.shape}")

    train_dataset = LSTM_BEKK_MODEL.ReturnDataset(dm_train_returns, seq_len=lstm_seq_len)
    val_dataset = LSTM_BEKK_MODEL.ReturnDataset(dm_val_returns, seq_len=lstm_seq_len)
    test_dataset = LSTM_BEKK_MODEL.ReturnDataset(dm_test_returns, seq_len=lstm_seq_len)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    # Initialize model
    print("Initializing LSTM-BEKK Model...")
    model = LSTM_BEKK_MODEL.LSTMBEKKModel(
        n_assets=n_assets,
        hidden_size=n_assets,
        num_layers=3,
        dropout=0.1
    ).to(device)

    print(f"Model parameters: {sum(p.numel() for p in model.parameters())} total parameters")

    # Initialize trainer
    trainer = LSTM_BEKK_MODEL.LSTMBEKKTrainer(model, learning_rate=0.001)

    # Train model
    train_losses, val_losses = trainer.train(
        train_loader, val_loader, epochs=30, patience=15
    )

    avg_nll_test = LSTM_BEKK_MODEL.evaluate_model(model, test_loader)
    nll_tests.append(avg_nll_test)

    window = torch.tensor(window, dtype=torch.float32).unsqueeze(0)
    forecasts = model.forecast(window, n_steps=horizon, sampling=True)
    lstm_pred_covs.append(forecasts)

    break


Using device: cpu


  0%|          | 0/26 [00:00<?, ?it/s]

Data shapes: Train = (4560, 3), Val = (1140, 3), Test = (250, 3)
Initializing LSTM-BEKK Model...
Model parameters: 324 total parameters
Starting LSTM-BEKK training...
Model parameters: a = 0.0498, b = 0.9048
Epoch 1/30: Train loss = 195.904372; Val loss = 204.291631
Epoch 2/30: Train loss = 178.793748; Val loss = 201.762875
Epoch 3/30: Train loss = 173.628709; Val loss = 202.268905
Epoch 4/30: Train loss = 171.908654; Val loss = 202.586441
Epoch 5/30: Train loss = 171.238877; Val loss = 202.489301
Epoch 6/30: Train loss = 170.793130; Val loss = 201.843272
Epoch 7/30: Train loss = 170.310613; Val loss = 200.876811
Epoch 8/30: Train loss = 169.583370; Val loss = 199.230259
Epoch 9/30: Train loss = 168.104293; Val loss = 195.558721
Epoch 10/30: Train loss = 165.413701; Val loss = 190.228392
Epoch 11/30: Train loss = 162.482434; Val loss = 186.512701
Epoch 12/30: Train loss = 159.822644; Val loss = 183.921270
Epoch 13/30: Train loss = 157.268280; Val loss = 181.636728
Epoch 14/30: Train lo

  0%|          | 0/26 [1:12:59<?, ?it/s]


In [24]:
lstm_pred_covs

[[tensor([[[0.9455, 0.8339, 0.9978],
           [0.8339, 2.3031, 2.3813],
           [0.9978, 2.3813, 2.6480]]]),
  tensor([[[1.4094, 1.6601, 1.7322],
           [1.6601, 3.2045, 3.2861],
           [1.7322, 3.2861, 3.5058]]]),
  tensor([[[0.6882, 0.9536, 1.0020],
           [0.9536, 2.4619, 2.5140],
           [1.0020, 2.5140, 2.7279]]]),
  tensor([[[1.1308, 1.3641, 1.4088],
           [1.3641, 2.8395, 2.8861],
           [1.4088, 2.8861, 3.0993]]]),
  tensor([[[0.8956, 1.1184, 1.1634],
           [1.1184, 2.5847, 2.6317],
           [1.1634, 2.6317, 2.8448]]]),
  tensor([[[1.2942, 1.5144, 1.5596],
           [1.5144, 2.9788, 3.0260],
           [1.5596, 3.0260, 3.2391]]]),
  tensor([[[0.7075, 0.9271, 0.9723],
           [0.9271, 2.3911, 2.4382],
           [0.9723, 2.4382, 2.6513]]]),
  tensor([[[0.7575, 0.9769, 1.0222],
           [0.9769, 2.4409, 2.4880],
           [1.0222, 2.4880, 2.7011]]]),
  tensor([[[3.6957, 3.9151, 3.9604],
           [3.9151, 5.3790, 5.4262],
           [3.

In [14]:
with open(os.path.join("lstm_results", f"lstm_pred_covs_{lstm_seq_len}seq_{data_returns.shape[1]}A_{horizon}S.pkl"), "wb") as f:
    pickle.dump(lstm_pred_covs, f)

In [ ]:
lstm_pred_covs 

[[tensor([[[12.4256, -8.6561, -0.0377],
           [-8.6561, 31.7176, 13.2909],
           [-0.0377, 13.2909, 14.6981]]]),
  tensor([[[16.9108, -4.1148,  4.4820],
           [-4.1148, 36.1139, 17.7980],
           [ 4.4820, 17.7980, 19.1450]]]),
  tensor([[[16.3625, -4.6160,  3.9623],
           [-4.6160, 35.4907, 17.2679],
           [ 3.9623, 17.2679, 18.5646]]]),
  tensor([[[15.9536, -4.9853,  3.5773],
           [-4.9853, 35.0188, 16.8742],
           [ 3.5773, 16.8742, 18.1287]]]),
  tensor([[[16.3383, -4.5673,  3.9820],
           [-4.5673, 35.3504, 17.2716],
           [ 3.9820, 17.2716, 18.4907]]]),
  tensor([[[18.1277, -2.7501,  5.7880],
           [-2.7501, 37.0950, 19.0715],
           [ 5.7880, 19.0715, 20.2608]]]),
  tensor([[[18.6087, -2.2455,  6.2831],
           [-2.2455, 37.5384, 19.5616],
           [ 6.2831, 19.5616, 20.7256]]]),
  tensor([[[18.7357, -2.0988,  6.4219],
           [-2.0988, 37.6337, 19.6960],
           [ 6.4219, 19.6960, 20.8389]]]),
  tensor([[[18.8